import gersangImg from "./images/data-images/image-gersang.png";
import mergeTabsImg from "./images/data-images/image-merge-tabs.jpg"
import wonderWordsGamesImg from "./images/data-images/image-wonderwords2.png"
import roleGameImg from "./images/data-images/role-game.png"
import tingDogImg from "./images/data-images/tingdog.png"
import warGameImg from "./images/data-images/war-game.png"
import colorSchemeGeneratorImg from "./images/data-images/colorschemegenerator.png"
import foodOrderingImg from "./images/data-images/food-ordering.png"
import memeGeneratorImg from "./images/data-images/meme-generator.png"
import movieWatchlistImg from "./images/data-images/movie-watchlist.png"
import pictureWebsiteImg from "./images/data-images/picture-website.png"
import game1Img from "./images/data-images/game1.jpg"
 
export default [
  
  {
    slug: "gersang-automation",
    type: "application",
    projectImg:gersangImg,
    title: "Gersang Automation with YOLOv4-tiny",
    description: "An automation project for the game 'Gersang' using YOLOv4-tiny and OpenCV.",
    fullDescription: "An automation project for the game Gersang using YOLOv4-tiny and OpenCV. It detects in-game elements via a custom-trained object detection model, captures game window screenshots, and automates clicks for farming tasks.",
    githubUrl: "https://github.com/kwfg/yolov4-tiny-opencv-gersang-automation",
    liveUrl: "https://www.youtube.com/watch?v=k_GV45inPjE",
    skill: ["Python", "YOLOv4", "OpenCV","GoogleColab"],
    isLive: true,
    isFeatured: true,
  },
  {
    slug: "blogsiem",
    type: "website",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/196557971-dd9e2a30-b402-4efe-90a9-32c28199dc3f.png",
    title: "BlogSiem",
    description:
      "Blog content management system (CMS) with the CRUD features. In addition, through simple Security information and event management (SIEM).",
    fullDescription:"Blog content management system (CMS) with the CRUD features. In addition, through simple Security information and event management (SIEM) to monitoring the whole website (collect logs, events), and detected Cross-site scripting (XSS), SQL Injection, Spam script. Then process some analysis and catch visitor details information.",
    githubUrl: "https://github.com/gakary/blogSiem",
    liveUrl: "",
    skill: ["HTML", "CSS", "PHP", "Boostrap", "GoogleChart", "API"],
    isLive: false,
    isFeatured: true,
  },
  {
  slug: "wonder-words-games",
  type: "website",
  projectImg: wonderWordsGamesImg,
  title: "Wonder Words Games - Official Website",
  description: "Official website for Wonder Words Games.",
  fullDescription:"Official website for Wonder Words Games, an indie game studio showcasing mobile games and creative projects.",
  githubUrl: "",
  liveUrl: "https://wonderwordsgames.com/",
  skill: ["React"],
  isLive: true,
  isFeatured: false,
  },
  {
  slug: "backroom-loop",
  type: "Game",
  projectImg: game1Img,
  title: "BACKROOM LOOP",
  description: "A psychological horror game released on Steam.",
  fullDescription:
    "BACKROOM LOOP is a psychological horror game set in an endless office-like maze. I was involved in QA testing, bug reporting, and helped design puzzle flow and spatial layouts for several levels. This game is available on <a href='https://store.steampowered.com/app/3672540/BACKROOM_LOOP/' target='_blank'>Steam</a>.",
  githubUrl: "",
  liveUrl: "https://youtu.be/o5LWAysrkQQ",
  skill: ["GameQA", "LevelDesign", "Unity"],
  isLive: true,
  isFeatured: true,
  },
  {
  slug: "merge-tabs",
  type: "application",
  projectImg: mergeTabsImg,
  title: "Merge Tabs Into One",
  description: "A simple Chrome extension that merges all your open tabs into a single window with one click.",
  fullDescription:"A simple Chrome extension that merges all your open tabs into a single window with one click, helping reduce tab clutter and improve productivity. It has been released on the Chrome Web Store.",
  githubUrl: "https://github.com/kwfg/MergeTabsIntoOne",
  liveUrl: "https://chromewebstore.google.com/detail/merge-tabs-into-one/kghpdnenhilgnagliakjophemjehhnji?utm_source=ext_app_menu",
  skill: ["JavaScript", "HTML", "ChromeAPI"],
  isLive: true,
  isFeatured: true,
  },
  {
    slug: "marketsmartbuy",
    type: "website",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/229617478-0fa3693e-9c63-4871-889c-a801349ff87d.PNG",
    title: "MarketSmartBuy",
    description:
      "The project was developed based on the concept of a smart district and is designed to improve daily work efficiency. Project focuses on the development of market and centralized data processing systems.",
    fullDescription:"The project was developed based on the concept of a smart district and is designed to improve daily work efficiency. It focuses on the development of market systems and centralized data processing. The project was awarded a Certificate of Merit in the IT Smart District Project Competition (Hong Kong General Chamber of Commerce, 2020).",  
    githubUrl: "https://github.com/gakary/MarketSmartBuy",
    liveUrl: "",
    skill: ["HTML", "CSS", "PHP", "API", "MySQL"],
    isLive: false,
  },
  {
    slug: "hkid-booking-system",
    type: "website",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/229857960-472da7d8-82a3-4e32-8172-5df9071d3f1f.png",
    title: "HKID Booking System",
    description:
      "The system is used to book to apply or replace the id card. (security project)",
    fullDescription:"This security-focused ID card booking system incorporates multiple protection layers, including form validation with regular expressions and captchas, prepared SQL statements, OpenSSL encryption/decryption for sensitive data, password hashing with salt, input sanitization using mysqli_real_escape_string and htmlspecialchars, and hidden PHP errors via php.ini to enhance overall data security.",  
    githubUrl: "https://github.com/gakary/idcard-booking-system",
    liveUrl: "",
    skill: ["HTML", "CSS", "PHP", "MySQL"],
    isLive: false,
  },
  {
    slug: "film-api",
    type: "api",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/229866597-7d21dd3c-c00f-4b7f-8fee-46f632d4097e.PNG",
    title: "Film API",
    description: "A restful API - Film Website",
    fullDescription: "A restful API - Film Website with MongoDB",
    githubUrl: "https://github.com/gakary/Restful_WebAPI",
    liveUrl: "",
    skill: ["NodeJS", "MongoDB"],
    isLive: false,
  },
  {
    slug: "picture-website",
    type: "website",
    projectImg:pictureWebsiteImg,
    title: "Picture Website",
    description: "Seaching picture via Pexels API",
    fullDescription:"The purpose of practicing React is to implement picture searching via the Pexels API.",
    githubUrl: "https://github.com/gakary/react-pictureWebsite-via-api",
    liveUrl: "",
    skill: ["SASS", "ReactJS"],
    isLive: false,
  },
  {
    slug: "wood-carving",
    type: "mobile",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/196564622-f496aceb-64b3-4a37-8176-5eca893831f7.PNG",
    title: "Wood Carving",
    description:
      "A mobile application that helps the Wood Carving Technique traditional industry survive in the 21st-century business environment.",
    fullDescription:"designed a mobile application to help the Wood Carving Technique traditional industry survive in the 21st-century business environment. It provides a platform that promotes the culture. The Application that called 'NewWood'. The whole project basically developed in Kotlin and sotre data in Firebase",  
    githubUrl: "https://github.com/gakary/WoodCarving",
    liveUrl: "",
    skill: ["Kotlin","Firebase"],
    isLive: false,
  },
  {
    slug: "password-generator",
    type: "website",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/218912628-b9b19251-2b47-48ea-b30a-abf530c9be83.PNG",
    title: "Password generator",
    description: "Simple password generator",
    fullDesctiption:"Simple password generator that randomly generates a password.",
    githubUrl: "https://github.com/gakary/password-generator",
    liveUrl: "https://melodious-starlight-74c8d7.netlify.app/",
    skill: ["HTML", "CSS", "JavaScript"],
    isLive: true,
  },
  {
    slug: "war-game",
    type: "website",
    projectImg:warGameImg,
    title: "War Game",
    description: "A card game made using the deckofcardsapi",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/wargame",
    liveUrl: "https://gentle-mochi-9b29ba.netlify.app/",
    skill: ["HTML", "CSS", "JavaScript", "API"],
    isLive: true,
  },
  {
    slug: "unit-converter",
    type: "website",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/229862254-7285c935-fc8f-44e9-84ff-e35d99849c0a.PNG",
    title: "Unit converter",
    description: "A unit converter that converts common units of measurement",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/unit-converter",
    liveUrl: "https://dancing-genie-ce4188.netlify.app/",
    skill: ["HTML", "CSS", "JavaScript"],
    isLive: true,
  },
  {
    slug: "movie-watchlist",
    type: "website",
    projectImg:movieWatchlistImg,
    title: "Movie Watchlist",
    description: "A movies search & watchlist via OMDb API",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/movieWatchlist",
    liveUrl: "https://vermillion-faloodeh-7f92c9.netlify.app/",
    skill: ["HTML", "CSS", "JavaScript", "API"],
    isLive: true,
  },
  {
    slug: "newtabdashboard",
    type: "application",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/226553672-fc34ddef-8870-41d3-801f-9ac1fdadee85.PNG",
    title: "newTabDashboard",
    description: "A Chrome extension (used to practice JS)",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/newTabDashboard",
    liveUrl: "",
    skill: ["HTML", "CSS", "JavaScript", "API"],
    isLive: false,
  },
  {
    slug: "worktabs",
    type: "application",
    projectImg:
      "https://user-images.githubusercontent.com/66684175/230964110-b146791d-fa9d-4c74-98c2-33001775dbe7.PNG",
    title: "workTabs",
    description:
      "A Google Chrome extension is used to bookmark websites for today's work.",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/workTabs",
    liveUrl: "",
    skill: ["HTML", "CSS", "JavaScript"],
    isLive: false,
  },
  {
    slug: "colorschemegenerator",
    type: "website",
    projectImg:colorSchemeGeneratorImg,
    title: "colorSchemeGenerator",
    description: "Genera the colour scheme via the colorAPI",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/colorSchemeGenerator",
    liveUrl: "https://tourmaline-semolina-ae5465.netlify.app/",
    skill: ["HTML", "CSS", "JavaScript", "API"],
    isLive: true,
  },
  {
    slug: "tingdog",
    type: "website",
    projectImg:tingDogImg,
    title: "Tingdog",
    description:
      "Tindog is a social app to understand its purpose is to give the suggestions of dogs and their owners. By location, the dog breed and other dog breeding pairings",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/tindog",
    liveUrl: "https://fancy-gnome-57f825.netlify.app/",
    skill: ["HTML", "CSS", "JavaScript"],
    isLive: true,
  },
  {
    slug: "meme-generator",
    type: "website",
    projectImg:memeGeneratorImg,
    title: "Meme Generator",
    description: "A meme generator",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary?tab=repositories",
    liveUrl: "https://sensational-kangaroo-0d7de3.netlify.app/",
    skill: ["CSS", "ReactJS", "API"],
    isLive: true,
  },
  {
    slug: "food-ordering",
    type: "website",
    projectImg:foodOrderingImg,
    title: "Food Ordering",
    description:
      "A Javascript exercise that orders the food and counts the total price, then purchases.",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/restaurant-orderingApp",
    liveUrl: "https://graceful-hamster-1b964c.netlify.app/",
    skill: ["HTML", "CSS", "JavaScript"],
    isLive: true,
  },
  {
    slug: "role-game",
    type: "website",
    projectImg:roleGameImg,
    title: "Role Game",
    description:
      "A Javascript exercise that hero fighting with demons simple game.",
    fullDescription:"A mini project designed solely for practicing JavaScript.",
    githubUrl: "https://github.com/gakary/rolePlaying-game",
    liveUrl: "https://gregarious-blancmange-1551e8.netlify.app/",
    skill: ["HTML", "CSS", "JavaScript"],
    isLive: true,
  },
];
